English translation
ToulouseJAM/workshop-resources pull request #5
Opened 2017-06-18 14:19 UTC by batmat

Superseding https://github.com/ToulouseJAM/workshop-resources/pull/4

Though now I think of it, I'm wondering if we want to keep both. Possibly not.

2017-06-18 20:09 UTC, mpailloncy requested changes

2017-06-18 20:09 UTC, mpailloncy commented on workshop2.adoc
> +1. Open your SonarQube instance: the default credentials are admin/admin. Changez directement le mot de passe de l'utilisateur admin.
manque la 2ème partie de la phrase à traduire

2017-06-18 20:09 UTC, mpailloncy commented on workshop2.adoc
> +5. As Jenkins reuses workspaces by default when possible, it's recommended to always cleanup workspaces when using steps like `unstash` to make sure the WS is clean each time and avoid issues.
Petit détails, je n'utiliserais pas "WS" ici => plus clair avec workspace

2017-06-18 20:12 UTC, mpailloncy commented on README.adoc
>  == Prérequis
Prerequisites

2017-06-18 20:12 UTC, mpailloncy commented on README.adoc
>  == Ateliers
=> workshops

2017-06-18 20:12 UTC, mpailloncy commented on README.adoc
> +=== Articles & Vidéos
Videos

2017-06-19 11:05 UTC, mpailloncy approved these changes

2017-06-19 11:24 UTC, merged

2017-06-19 11:24 UTC, batmat commented
\o/